name = "clm-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "clm"
database_id = "4c756639-4a89-442d-b228-0dd79749ed85"

[version_metadata]
binding = "CF_VERSION_METADATA"
